### PR TITLE
[Improvements] Added .ruby-version for `rbenv` local use

### PR DESCRIPTION
**Pull request by james2791**
For folks using `rbenv`, you can set a local version specific to a repo/dir on the host to switch versions to/from

I'm of this type - but for anyone else running/managing the CLI with `rbenv` with a local version set in the migrations repo, this dotfile will be referred to when using the tool!

### CODE REVIEW

**Comment by toote** [comment]
why not just add the `.ruby-version` file to the repository instead? That way people using rbenv will be able to take advantage of it

**Comment by james2791** [comment]
> why not just add the `.ruby-version` file to the repository instead? That way people using rbenv will be able to take advantage of it

I've now accounted for the other way - _adding_ the dotfile! 😄

**Review by toote — COMMENTED** [review]
I'd rather the version matches the one in the Dockerfile but definitely not critical at this time

**Review by toote — APPROVED** [review]
(sorry meant to approve it while leaving the comment)

**Comment by james2791** [comment]
I've also matched the base image back to `3.2.2` - matching the dotfile add 👍

**Pull request merged**
